### ISSUE TITLE
Derived/cached properties in dataclasses

### ISSUE THREAD

**Issue by simonbowly** [simonbowly/math-code-guidelines#2]
@stevedwards this seemed like a good idea at the time, but I'm not sure `lru_cache` should be best practice since it has to hash the object and create a dictionary just to store one result... will come up with a neater solution.

https://github.com/simonbowly/math-code-guidelines/blob/9904f1a0f724a52ff6c538c462bfd7ab56d1258a/examples/crossdock/crossdock/instance.py#L54-L56

**Comment by stevedwards** [comment]
Maybe its worth creating a new section on decorators all together...
